apiVersion: v1
kind: Secret
metadata:
  name: example-extension
  labels:
    # this label is the unique name of the extension
    argocd.argoproj.io/extension: example
stringData:
  # the target URL for requests
  url: http://example-extension:3983
  # headers to add to each request
  headers: |
    # may from header name to array of values (it is very rare to have >1 value)
    Authorization: 
    - Bearer LetMeIn
  # paths that this extension supports
  paths: |
    # the path, this will become /api/extensions/example/application/my-app
    "/applications/{application}":
      GET: 
        # RBAC resource name: clusters,projects,applications,repositories,certificates,accounts,gpgkeys,logs
        resource: applications
        # RBAC action: get,create,update,delete,sync,override,actino
        action: get
        # RBAC object: this must be in the path with curly-braces, e.g. {application}
        object: application